---
title: "Peer Review Three"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
#runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)

dat<-read_csv(url("https://www.dropbox.com/s/4ebgnkdhhxo5rac/cel_volden_wiseman%20_coursera.csv?raw=1"))

dat$Party<-recode(dat$dem,`1`="Democrat",`0`="Republican")


#######HINT: for Chart D, you'll need to set the height of the renderPlot, using the height argument. Try a value of 750.

#####some data management functions are already included. You need to add the visualization functions.

```

Page 1 {data-orientation=row}
================================

### Chart A

```{r}
dat %>% 
  drop_na() %>% 
  filter(year>1979) %>% 
  group_by(year,Party) %>% 
  summarise(passed=sum(all_pass)) %>%
  ggplot(aes(x=year, y=passed, fill=Party)) + 
  geom_area() +
  ggtitle("The Number of Bills Passed Since 1980") +
  labs(y = "All Bill Passed",
       x = "Year") +
  scale_fill_manual(values = c("blue","red"))

```

Column {data-width=650}
-----------------------------------------------------------------------

Page 2  {data-orientation=column}
===============================

### Chart B

```{r}

test3 <- dat%>%
  drop_na()%>%
  filter(congress==110)

p <- ggplot(test3,
            aes(x=votepct, y=all_pass, label=thomas_name, color=Party))+
            geom_smooth(method="lm")+
            geom_point()+ 
            labs(x = "Vote Pct.", y = "All Pass" , title = "Passage and Vote Pct., 110th Congress") +
            scale_color_manual(values = c("blue", "red"))

ggplotly(p)

```

### Chart C

```{r}

test2 <- dat%>%
          drop_na()%>%
          filter(congress==110)

ggplotly(ggplot(test2,
                aes(x=dwnom1, y=all_pass, label=thomas_name, color=Party))+
           geom_smooth(method="lm")+
           geom_point()+ 
           labs(x = "DW Nominates", y = "All Pass" , title = "Passage and Ideology, 110th Congress") +
           scale_color_manual(values = c("blue", "red")))

```

Column {data-width=350}
-----------------------------------------------------------------------


Page 3
======

### Chart D

```{r}

####hint: this figure uses selectInput with the multiple option set to true and with the options set up so that all states are initially selected.


dat %>% 
  group_by(st_name) %>% 
  filter(congress==110) %>%
  summarise(passed=sum(all_pass))
```
